### ISSUE TITLE
missing crust folder with its gulpfile when creating book

### ISSUE THREAD

**Issue by crcdd** [swzzl-com/bookiza.cli#5]
Hi

I was trying to update bookiza from 0.0.1 (or 0.0.11) and i noticed i had to update node aswell. After doing that i installed bookiza 0.1.1. That went well without errors.  I then tried to add a new book, but then i got the following errors below. 

I'm running nvm 0.33.2 with nodejs at version 7.10.0
Gulp is at 3.9.1 and npm is 4.2.0

Error:

> $ bookiza new mybook20 --leafs 12
> Initializing…  [ manuscript=mybook20 | leafs=12 | template=blank ]
> Copying crust failed Error: ENOENT: no such file or directory, lstat '/Users/Dieuwert/.nvm/versions/node/v7.10.0/lib/node_modules/bookiza/crust'
> License.txt… :added.
> README initialization… :success.
> .gitignoring /build /node_modules… :done.
> Applying a blank layout… :success.
> Arcvalues & Package Json unavailable Error: Did not find the arc!
> Failed. Gulpfile unavailable. Error: ENOENT: no such file or directory, link 'crust/gulpfile.js' -> 'gulpfile.js'

I'm missing out on a crust folder and a gulpfile, compared to the book that i had from an older bookiza version. What can i do to see the book running with "bookiza server" locally? Right now it won't run.

**Comment by marvindanig** [comment]
Hey @crcdd yes! 

Bookiza isn't functional at the moment because I'm kinda focused on writing a replacement for Turnjs (which isn't supported anymore *and* not available on a license it used to be.) in pure javascript. 

Here's the repository for [FlippyJS](https://github.com/marvindanig/flippy.JS) and I welcome you to contribute in anyway you can! :-)
